# Generated by Django 5.2.17 on 2026-08-25 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("inventory", "0001_initial"),
        ("pos", "0002_salestransaction_amount_tendered_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("SALE_DEDUCTION", "Sale Deduction"),
                            ("MANUAL_ADJUSTMENT", "Manual Adjustment"),
                        ],
                        max_length=32,
                    ),
                ),
                ("quantity_change", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="accounts.branch"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="inventory.product"
                    ),
                ),
                (
                    "related_sales_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pos.salesitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("quantity_on_hand", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="accounts.branch"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="inventory.product"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Inventory",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("branch", "product"), name="unique_inventory_per_branch_product"
                    )
                ],
            },
        ),
    ]
