# Generated by Django 5.2.17 on 2026-08-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_inventorytransaction_inventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[("FINISHED_GOOD", "Finished Good"), ("MATERIAL", "Raw Material")],
                default="FINISHED_GOOD",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="reorder_threshold",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
