# Generated by Django 5.2.17 on 2026-08-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_product_product_type_product_reorder_threshold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorytransaction",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("SALE_DEDUCTION", "Sale Deduction"),
                    ("MANUAL_ADJUSTMENT", "Manual Adjustment"),
                    ("PRODUCTION_CONSUMPTION", "Production Consumption"),
                    ("PRODUCTION_OUTPUT", "Production Output"),
                ],
                max_length=32,
            ),
        ),
    ]
