# Generated by Django 5.2.17 on 2026-09-09 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_inventorytransaction_movement_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COFFEE", "Coffee"),
                    ("COFFEE_FRAPPE", "Coffee Frappe"),
                    ("NON_COFFEE_FRAPPE", "Non-Coffee Frappe"),
                    ("SEA_SALT_SERIES", "Sea Salt Series"),
                    ("SPECIALTY", "Specialty"),
                    ("BREAKFAST", "Breakfast"),
                    ("PASTA", "Pasta"),
                    ("DESSERTS", "Desserts"),
                    ("CAKES", "Cakes"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_best_seller",
            field=models.BooleanField(default=False),
        ),
    ]
