# Generated by Django 5.2.17 on 2026-09-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_product_category_product_is_best_seller"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="large_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
