# Generated by Django 5.2.17 on 2026-10-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_product_large_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COFFEE", "Coffee"),
                    ("COFFEE_FRAPPE", "Coffee Frappe"),
                    ("NON_COFFEE_FRAPPE", "Non-Coffee Frappe"),
                    ("SEA_SALT_SERIES", "Sea Salt Series"),
                    ("SPECIALTY", "Specialty"),
                    ("BREAKFAST", "Breakfast"),
                    ("PASTA", "Pasta"),
                    ("DESSERTS", "Desserts"),
                    ("CAKES", "Cakes"),
                    ("BAKERY", "Bakery & Pasalubong"),
                ],
                max_length=32,
            ),
        ),
    ]
