# Generated by Django 5.2.17 on 2026-08-29 12:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusinessSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "business_name",
                    models.CharField(default="Jorge's Casa De Sans Rival", max_length=150),
                ),
                ("business_address", models.CharField(blank=True, max_length=255)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                (
                    "tax_rate_percent",
                    models.DecimalField(decimal_places=2, default=Decimal("12.00"), max_digits=5),
                ),
                ("currency_symbol", models.CharField(default="₱", max_length=5)),
                (
                    "receipt_footer_text",
                    models.CharField(
                        blank=True, default="Thank you for your purchase!", max_length=255
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "admin_alert_email",
                    models.EmailField(
                        blank=True,
                        help_text="Where scheduled-job failure alerts are sent. Falls back to Django's ADMINS setting if left blank.",
                        max_length=254,
                    ),
                ),
                (
                    "ai_insights_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="When off, insight generation always uses the template fallback -- no live AI API calls are made at all, regardless of whether an API key is configured.",
                    ),
                ),
                ("high_risk_days_threshold", models.PositiveIntegerField(default=3)),
                ("medium_risk_days_threshold", models.PositiveIntegerField(default=10)),
                ("default_forecast_days", models.PositiveIntegerField(default=7)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
