# Generated by Django 5.2.17 on 2026-08-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="is_commissary",
            field=models.BooleanField(
                default=False,
                help_text="True only for the centralized commissary (Phase 1 §1.1). Modeled as a Branch row so Production (Week 8) can reuse existing branch-scoping, selection, and Inventory infrastructure rather than a parallel system.",
            ),
        ),
    ]
