# Generated by Django 5.2.17 on 2026-09-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_twofactorbackupcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashierpin",
            name="failed_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cashierpin",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
