# Generated by Django 5.2.17 on 2026-08-28 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_branch_is_commissary"),
        ("inventory", "0004_alter_inventorytransaction_movement_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Forecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "forecast_date",
                    models.DateField(help_text="The future date this prediction is for."),
                ),
                ("predicted_quantity", models.FloatField()),
                ("model_used", models.CharField(max_length=50)),
                ("mae", models.FloatField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.branch"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inventory.product"
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at", "forecast_date"],
            },
        ),
    ]
