# Generated by Django 5.2.17 on 2026-08-29 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_branch_is_commissary"),
        ("forecasting", "0001_initial"),
        ("inventory", "0004_alter_inventorytransaction_movement_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("STOCKOUT_WARNING", "Stockout Warning"),
                            ("DEMAND_SUMMARY", "Demand Summary"),
                        ],
                        max_length=32,
                    ),
                ),
                ("message", models.TextField()),
                ("generated_by_ai", models.BooleanField(default=False)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.branch"
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryRiskScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "quantity_on_hand",
                    models.IntegerField(help_text="Stock snapshot at classification time."),
                ),
                ("avg_daily_demand", models.FloatField()),
                (
                    "days_of_stock_left",
                    models.FloatField(
                        blank=True,
                        help_text="Null when demand is zero (stock never runs out).",
                        null=True,
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.branch"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inventory.product"
                    ),
                ),
            ],
            options={
                "ordering": ["-computed_at"],
            },
        ),
    ]
