# Generated by Django 5.2.17 on 2026-08-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salestransaction",
            name="amount_tendered",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="salestransaction",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("CASH", "Cash"), ("GCASH", "GCash"), ("CARD", "Card")],
                max_length=32,
            ),
        ),
    ]
