# Generated by Django 5.2.17 on 2026-09-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0002_salestransaction_amount_tendered_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddOn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
