# Generated by Django 5.2.17 on 2026-09-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0003_addon"),
    ]

    operations = [
        migrations.AddField(
            model_name="salestransaction",
            name="dining_option",
            field=models.CharField(
                choices=[("DINE_IN", "Dine-in"), ("TAKE_OUT", "Take-out")],
                default="DINE_IN",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="salestransaction",
            name="transaction_discount_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="salestransaction",
            name="transaction_discount_category",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="salestransaction",
            name="transaction_discount_type",
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
