# Generated by Django 5.2.17 on 2026-09-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0004_salestransaction_dining_option_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salestransaction",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("CASH", "Cash"), ("GCASH", "GCash"), ("CARD", "Credit Card")],
                max_length=32,
            ),
        ),
    ]
